# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 015fac831252a3775580927ff5abd8d23e1e0d1e28aacaf1df66f8390631d41132ddf2b486f1bce5668ed0ddc0119beec2a00d80c5424bb59c72c1b6fe6446f7

test:
  secret_key_base: 9cb1098e9fea4f78389aa72d7b0b73a8323e0ba2ab6a3e84d744ddaae3d6cec23a65e703246d5e082376baed448253f863f93350010331aa8a8c62a1623ebdd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
